substitutions: 
  name: smart-sense-speaker
  friendly_name: Smart Sense Speaker
  name_add_mac_suffix: false


############# END OF SUBSTITUTIONS #################
####################################################

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0
  name_add_mac_suffix: ${name_add_mac_suffix}

  project:
    name: "MacMadixx.smart-sense-speaker"
    version: "2025.02.01"

esp32:
  board: esp32-s3-devkitc-1
  # flash_size: 16MB  # Uncomment this line if you need to specify the flash size for your ESP32 board
  framework:
    type: esp-idf

    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
   
psram:
  mode: octal # Change this to quad for N8R2 and octal for N16R8
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid:  "${name} Fallback Hotspot"
    password: !secret ap_password

captive_portal:


################ MAIN COMPONENTS ###################
####################################################
light:
  - platform: esp32_rmt_led_strip
    
    id: led_ww
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "On board light"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%

button:
  - platform: template
    name: "Button 1"
    on_press:
      then:
        - logger.log: Button Pressed